// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5hBbMYREFmxfjiOQv9BkOPS-VYO_hdgY',
    appId: '1:162401462729:web:82f525e3412b5c97ee6018',
    messagingSenderId: '162401462729',
    projectId: 'aplicativo-autonomos',
    authDomain: 'aplicativo-autonomos.firebaseapp.com',
    storageBucket: 'aplicativo-autonomos.firebasestorage.app',
    measurementId: 'G-BZWLB311MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7sT00uI5CHROJ6YsbUnC9A5wLt--o1JI',
    appId: '1:162401462729:android:2ecf65d4ec457c32ee6018',
    messagingSenderId: '162401462729',
    projectId: 'aplicativo-autonomos',
    storageBucket: 'aplicativo-autonomos.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu-REgBpizl9MlzMMp4gXPlnRyw_E5OnE',
    appId: '1:162401462729:ios:a51d0f6e81b326a1ee6018',
    messagingSenderId: '162401462729',
    projectId: 'aplicativo-autonomos',
    storageBucket: 'aplicativo-autonomos.firebasestorage.app',
    iosBundleId: 'com.example.projetoAutonomos',
  );
}
